### ISSUE TITLE
Unexpected error in AndroidAnnotations 4.1.0: AnnotationTypeMismatchException with EActivity

### ISSUE THREAD

**Issue by Sleeper9** [androidannotations/androidannotations#1902]
Suddenly I get this weird exception during compile. The strange thing is, that it only occurs on Linux environment, on Windows, everything works fine.
The relevant parts maybe:

```
Java version: javac 1.8.0_111
Javac processors options: androidManifestFile=/home/lilles/work/dev/misc/qualitygate4d/qualitygate4d/app/build/intermediates/manifests/full/full/debug/AndroidManifest.xml, resourcePackageName=com.frontendart.qualitygate.android
Stacktrace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.androidannotations.helper.AnnotationHelper.extractAnnotationParameter(AnnotationHelper.java:352)
at org.androidannotations.helper.AnnotationHelper.extractAnnotationResIdValueParameter(AnnotationHelper.java:317)
at org.androidannotations.helper.AnnotationHelper.extractAnnotationResIdValueParameter(AnnotationHelper.java:310)
at org.androidannotations.helper.IdValidatorHelper.resIdsExist(IdValidatorHelper.java:43)
at org.androidannotations.internal.core.handler.EActivityHandler.validate(EActivityHandler.java:52)
at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:65)
at org.androidannotations.internal.process.ModelValidator.validate(ModelValidator.java:73)
at org.androidannotations.internal.AndroidAnnotationProcessor.validateAnnotations(AndroidAnnotationProcessor.java:216)
at org.androidannotations.internal.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:174)
at org.androidannotations.internal.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:126)

...

Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract int org.androidannotations.annotations.EActivity.value() (Found data of type <any>)
at com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor$1AnnotationTypeMismatchExceptionProxy.generateException(AnnotationProxyMaker.java:269)
at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
at com.sun.proxy.$Proxy86.value(Unknown Source)
... 119 more
```

I checked, I only use @Eactivity() on AppCompatActivity classes, and with valid resource identifiers.

**Comment by Sleeper9** [comment]
Okay, sorry for the inconvinience, it was a user error, somehow an unversioned file remained in my codebase which I just slipped through at first; closing issue az invalid.
