### ISSUE TITLE
Setting an int as text into TextView, TextView resource xml not found anymore

### ISSUE THREAD

**Issue by beraldofilippo** [androidannotations/androidannotations#1948]
Hi, I've found a strange behavior when trying to put an int into a TextView, it compiles and runs, until it goes to the point of the assignment and states that the view (which is defined in xml) is not found anymore.

**AndroidAnnotations version**: 4.2.0

**Android compile SDK version**: 24

**Annotated code**:
```
   @ViewById
    protected TextView quantity;

   @AfterViews
   public void showUI() {
      quantity.setText(methodWhichReturnsAnInt());
   }

```

**Stacktrace in case of AA crash**: 
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: xxxxxxxxxxxx, PID: 16583
                                                                     android.content.res.Resources$NotFoundException: String resource ID #0x3
                                                                         at android.content.res.Resources.getText(Resources.java:321)
                                                                         at android.widget.TextView.setText(TextView.java:4135)
                                                                         at xxxxxxxxxxxx.mission.MissioneFragment.showUI(MissioneFragment.java:147)
                                                                         at xxxxxxxxxxxx.mission.MissioneFragment_.onViewChanged(MissioneFragment_.java:176)
                                                                         at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
                                                                         at xxxxxxxxxxxx.MissioneFragment_.onViewCreated(MissioneFragment_.java:88)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

That's a bit of annoying since it doesn't state clearly where the error comes from.

**Comment by WonderCsabo** [comment]
Sorry, but this error has nothing to do wit AA... The problem is that you are setting a resource identifier which does not exist. (`TextView.setText()` accepts a resource identifier, not just any integer.)
