### ISSUE TITLE
Crash com.app.APIs.ServiceGenerator.isConnected

### ISSUE THREAD

**Issue by trr-amsiq** [androidannotations/androidannotations#2000]
AA **4.3.0**:

SDK **1.7**:

Device **Accent Speed-y2**:

**Actual generated code**:
```java
//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.3.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package com.app.activities.startup;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import com.app.Fragments.Gallery.ViewPager.RtlViewPager;
import com.app.R;
import com.app.views.Auth.AuthContainer;
import com.app.views.Auth.AuthLogoItem;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.builder.PostActivityStarter;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class StartUpActivity_
    extends StartUpActivity
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private final IntentFilter intentFilter1_ = new IntentFilter();
    private final BroadcastReceiver networkChangesReceiver_ = new BroadcastReceiver() {

        public void onReceive(Context context, Intent intent) {
            StartUpActivity_.this.networkChanges();
        }
    }
    ;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(R.layout.activity_start_up);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        this.animation = AnimationUtils.loadAnimation(this, R.anim.beatingheart);
        restoreSavedInstanceState_(savedInstanceState);
        intentFilter1_.addAction("android.net.conn.CONNECTIVITY_CHANGE");
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static StartUpActivity_.IntentBuilder_ intent(Context context) {
        return new StartUpActivity_.IntentBuilder_(context);
    }

    public static StartUpActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new StartUpActivity_.IntentBuilder_(fragment);
    }

    public static StartUpActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new StartUpActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.root = ((FrameLayout) hasViews.findViewById(R.id.root));
        this.base = ((FrameLayout) hasViews.findViewById(R.id.base));
        this.loginLayout = ((LinearLayout) hasViews.findViewById(R.id.loginLayout));
        this.beating_item = ((AuthLogoItem) hasViews.findViewById(R.id.beating_item));
        this.login = ((Button) hasViews.findViewById(R.id.login));
        this.upperPager = ((RtlViewPager) hasViews.findViewById(R.id.upperPager));
        this.authContainer = ((AuthContainer) hasViews.findViewById(R.id.authContainer));
        this.facebookImage = ((ImageView) hasViews.findViewById(R.id.facebookImage));
        if (this.login!= null) {
            this.login.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    StartUpActivity_.this.login();
                }
            }
            );
        }
        afterViews();
        init();
    }

    @Override
    public void onSaveInstanceState(Bundle bundle_) {
        super.onSaveInstanceState(bundle_);
        bundle_.putBoolean("shouldAutoSwipe", shouldAutoSwipe);
        bundle_.putInt("currentPage", currentPage);
        bundle_.putInt("autoScrollDirection", autoScrollDirection);
    }

    private void restoreSavedInstanceState_(Bundle savedInstanceState) {
        if (savedInstanceState == null) {
            return;
        }
        shouldAutoSwipe = savedInstanceState.getBoolean("shouldAutoSwipe");
        currentPage = savedInstanceState.getInt("currentPage");
        autoScrollDirection = savedInstanceState.getInt("autoScrollDirection");
    }

    @Override
    public void onResume() {
        super.onResume();
        this.registerReceiver(networkChangesReceiver_, intentFilter1_);
    }

    @Override
    public void onPause() {
        this.unregisterReceiver(networkChangesReceiver_);
        super.onPause();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<StartUpActivity_.IntentBuilder_>
    {
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, StartUpActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), StartUpActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), StartUpActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public PostActivityStarter startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode, lastOptions);
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        context.startActivity(intent, lastOptions);
                    }
                }
            }
            return new PostActivityStarter(context);
        }
    }
}
```

**Stacktrace in case of AA crash**:
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.app.activities.startup.StartUpActivity_$1@cab20a6
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:932)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.SecurityException: ConnectivityService: Neither user 10095 nor current process has android.permission.ACCESS_NETWORK_STATE.
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1075)
       at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:696)
       at com.app.APIs.ServiceGenerator.isConnected(ServiceGenerator.java:90)
       at com.app.activities.startup.StartUpActivity.networkChanges(StartUpActivity.java:550)
       at com.app.activities.startup.StartUpActivity_$1.onReceive(StartUpActivity_.java:44)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by dodgex** [comment]
This issue is not related to AndroidAnnotations.

> Caused by java.lang.SecurityException: ConnectivityService: Neither user 10095 nor current process has android.permission.ACCESS_NETWORK_STATE.

You need to ensure that your app has `android.permission.ACCESS_NETWORK_STATE` permisison by adding  `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` to your `AndoridManifest.xml`.

**Comment by trr-amsiq** [comment]
@dodgex But it is added like so:

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

I have more than 40K users a month and this has happened few times for users with Accent Speed-y2 devices.

**Comment by dodgex** [comment]
Well. Unfortunately it is still not an AndroidAnnotation related issue. It is a permission issue. Maybe the users have somehow revoked the `ACCESS_NETWORK_STATE` permission or it is some kind of issue with the rom on the related devices.

**Comment by trr-amsiq** [comment]
Alright thanks for the quick answer @dodgex
