### ISSUE TITLE
Could not find AndroidManifest.xml file using generation folder

### ISSUE THREAD

**Issue by iamMehedi** [androidannotations/androidannotations#2034]
Android build fails with this error message:
`Error:Could not find the AndroidManifest.xml file, using  generation folder [.../app/build/generated/source/apt/debug])`
The manifest file is actually located at: 
`.../app/build/intermediates/manifests/full/some_product_flavor/debug/AndroidManifest.xml`

**AndroidAnnotations version**: 4.3.1

**Android compile SDK version**: 26

Here's the gradle file contents: 
```groovy
def AAVersion = '4.3.1'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://jitpack.io" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'me.tatarka:gradle-retrolambda:3.7.0'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'realm-android'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'io.fabric'

repositories {
    jcenter()
    mavenCentral()
    mavenLocal()
    
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
}
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.1'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.company.appId"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode XX
        versionName "X.X.X"

        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

        jackOptions {
            enabled false
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            debuggable false
            signingConfig signingConfigs.XXX_Release

            ext.crashlyticsApiSecret = "apiSecret_release"
            ext.crashlyticsApiKey = "apiKey_release"
        }
        debug {
            debuggable true

            ext.crashlyticsApiSecret = "apiSecret_release"
            ext.crashlyticsApiKey = "apiKey_release"
        }
    }

    splits{
        abi {
            enable true
            reset()
            include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86', 'x86_64'
            universalApk false
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}

android.applicationVariants.all { variant ->
    variant.variantData.variantConfiguration.javaCompileOptions.annotationProcessorOptions
            .arguments = ['resourcePackageName': android.defaultConfig.applicationId,
                          'androidManifestFile': variant.outputs[0]?.processResources?.manifestFile.absolutePath]
    println "manifest option: ${variant.outputs[0]?.processResources?.manifestFile.absolutePath}"
}

//region retroLambda utility
String getJavaVersion(Integer v) {
    def sout = new StringBuffer()
    def proc = "/usr/libexec/java_home -v 1.$v".execute()
    proc.consumeProcessOutput(sout, new StringBuffer())
    proc.waitForOrKill(1000)
    return sout.toString().replace("\n", "").replace("\r", "")
}

String java8 = getJavaVersion(8)
String java7 = getJavaVersion(7)

retrolambda {
    jvmArgs '-noverify'
    jdk java8
    oldJdk java7
    javaVersion JavaVersion.VERSION_1_7
}
//endregion

//region Fabric Utility
import com.crashlytics.tools.utils.PropertiesUtils

File crashlyticsProperties = new File("${project.projectDir.absolutePath}/fabric.properties")
android.applicationVariants.all { variant ->
    def variantSuffix = variant.name.capitalize()
    def generateResourcesTask = project.tasks.getByName("fabricGenerateResources${variantSuffix}")
    def generatePropertiesTask = task("fabricGenerateProperties${variantSuffix}") << {
        Properties properties = new Properties()
        println "...copying apiSecret for ${variant.name}"
        properties.put("apiSecret", variant.buildType.ext.crashlyticsApiSecret)
        println "...copying apiKey for ${variant.name}"
        properties.put("apiKey", variant.buildType.ext.crashlyticsApiKey)
        PropertiesUtils.injectPropertyInFile(crashlyticsProperties, properties, "")
    }

    generateResourcesTask.dependsOn generatePropertiesTask
}
//endregion

dependencies {
    String playServicesVersion = '11.0.4'
    String supportLibVersion = '26.0.0'

    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.android.support:appcompat-v7:${supportLibVersion}"
    compile "com.android.support:cardview-v7:${supportLibVersion}"
    compile "com.android.support:recyclerview-v7:${supportLibVersion}"
    compile 'com.android.support:multidex:1.0.1'
    compile "com.android.support:design:${supportLibVersion}"
    compile "com.android.support:percent:${supportLibVersion}"

    //play services
    compile "com.google.android.gms:play-services-base:${playServicesVersion}"
    compile "com.google.android.gms:play-services-location:${playServicesVersion}"
    compile "com.google.android.gms:play-services-auth:${playServicesVersion}"

    compile "com.android.support:customtabs:${supportLibVersion}"

    //annotation
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"

    //for dagger 2
    compile 'com.google.dagger:dagger:2.11'
    provided 'org.glassfish:javax.annotation:10.0-b28'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.11'
    compile 'com.google.dagger:dagger-android:2.11'
    // if you use the support libraries
    compile 'com.google.dagger:dagger-android-support:2.11'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.11'

    //firebase
    compile "com.google.firebase:firebase-core:${playServicesVersion}"
    compile "com.google.firebase:firebase-messaging:${playServicesVersion}"
    compile "com.google.firebase:firebase-config:${playServicesVersion}"
    compile "com.google.firebase:firebase-storage:${playServicesVersion}"
    compile "com.google.firebase:firebase-auth:${playServicesVersion}"
    compile "com.google.firebase:firebase-database:${playServicesVersion}"
    compile "com.google.firebase:firebase-perf:${playServicesVersion}"

     ...
    //billing
    compile 'com.anjlab.android.iab.v3:library:1.0.39'
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "200"
    }
}

apply plugin: 'com.google.gms.google-services'
```

**Stacktrace in case of AA crash**:
```java
error: cannot find symbol for all annotation processor generated classes
...
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more
```

**Comment by dodgex** [comment]
While this looks like a duplicate to https://github.com/androidannotations/androidannotations/issues/2028 (similar issue with lates 3.0.0-alpha and kotlin build) I wonder why you find your manifest in `../app/build/intermediates/manifests/full/some_product_flavor/debug/AndroidManifest.xml` but no flavor config in your `build.gralde`?

**Comment by iamMehedi** [comment]
I think that's because of the APK split settings in gradle? 
```groovy
splits{
        abi {
            enable true
            reset()
            include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86', 'x86_64'
            universalApk false
        }
    }
```

**Comment by dodgex** [comment]
Maybe. If your `some_product_flavor` is not exactly `some_product_flavor` but eg. `armeabi`

**Comment by iamMehedi** [comment]
Exactly! It is actually not `product_flavor`, it's the architecture types i.e `armeabi`
<img width="238" alt="screen shot" src="https://user-images.githubusercontent.com/3691635/28910590-52fb9264-784f-11e7-8e9c-c8001568ea81.png">

**Comment by WonderCsabo** [comment]
@iamMehedi  to be clear, you do not have any product flavors at all, correct?

**Comment by dodgex** [comment]
Interesting. Could you try the 4.4.0-SNAPSHOT of Android Annotations? 

@WonderCsabo maybe we need to update https://github.com/androidannotations/androidannotations/pull/2030 to also search for the manifest when used with `apt` and not only `kapt`.

**Comment by WonderCsabo** [comment]
BTW, i cannot reproduce your issue. I just added this block to the Gradle example project:
```groovy
splits{
    abi {
        enable true
        reset()
        include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86', 'x86_64'
        universalApk false
    }
}
```

Execution of `assembleDebug` works fine. (There is a manifest generated at *intermediates/manifests/full/debug* as expected).

But if i add a flavor, it breaks, because the manifest is located at *intermediates/manifests/full/flavor1/{split}/debug* .

**Comment by iamMehedi** [comment]
@WonderCsabo yes, I don't have any product flavors at all. No universal apk is generated only the split ones and their version code is updated as follows:
```groovy
// Map for the version code that gives each ABI a value.
ext.abiCodes = ['armeabi':1, 'armeabi-v7a':2, 'arm64-v8a':3, 'mips':4, 'x86':5, 'x86_64':6]

// For per-density APKs, create a similar map like this:
// ext.densityCodes = ['mdpi': 1, 'hdpi': 2, 'xhdpi': 3]

import com.android.build.OutputFile

// For each APK output variant, override versionCode with a combination of
// ext.abiCodes * 1000 + variant.versionCode. In this example, variant.versionCode
// is equal to defaultConfig.versionCode. If you configure product flavors that
// define their own versionCode, variant.versionCode uses that value instead.
android.applicationVariants.all { variant ->

    // Assigns a different version code for each output APK
    // other than the universal APK.
    variant.outputs.each { output ->

        // Stores the value of ext.abiCodes that is associated with the ABI for this variant.
        def baseAbiVersionCode =
                // Determines the ABI for this variant and returns the mapped value.
                project.ext.abiCodes.get(output.getFilter(OutputFile.ABI))

        // Because abiCodes.get() returns null for ABIs that are not mapped by ext.abiCodes,
        // the following code does not override the version code for universal APKs.
        // However, because we want universal APKs to have the lowest version code,
        // this outcome is desirable.
        if (baseAbiVersionCode != null) {

            // Assigns the new version code to versionCodeOverride, which changes the version code
            // for only the output APK, not for the variant itself. Skipping this step simply
            // causes Gradle to use the value of variant.versionCode for the APK.
            output.versionCodeOverride =
                    baseAbiVersionCode * 100000 + variant.versionCode
        }
    }
}
```

**Comment by iamMehedi** [comment]
@WonderCsabo I was able to reproduce this error with the gradle example after updating the `compileSdkVersion` to 26 and `buildToolsVersion` to `26.0.1`
<img width="1117" alt="screen shot" src="https://user-images.githubusercontent.com/3691635/28913560-50002196-785a-11e7-9b8f-6f906672ee6c.png">

**Comment by WonderCsabo** [comment]
@iamMehedi i see, in that case, the `debug` folder undef `full` no longer present.

@dodgex yes we should enhance the manifest finder to work with splits as well.

**Comment by dodgex** [comment]
Looks like a change in the `26.x.y` tools.

**Comment by dodgex** [comment]
I'll see if i can get a hand on it in the next days.

**Comment by WonderCsabo** [comment]
@dodgex (if you are using flavors, it does not work even you are using `25.x.y` tools.)

**Comment by dodgex** [comment]
So without flavor the case of this issue works with 25.x.y but with flavor + split it does not work with 25?

**Comment by dodgex** [comment]
I wonder if we need to keep support for 25.x or if it is ok to build a solution that aims at buildtools 26 users.

**Comment by iamMehedi** [comment]
for my case the same setup is working if I use the `android-apt` (com.neenbedankt.gradle.plugins:android-apt:1.8) plugin with the following arguments 
```groovy
apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        resourcePackageName android.defaultConfig.applicationId
    }
}
```

**Comment by WonderCsabo** [comment]
We should aim to 26.x, however i think if you have flavors, the two are the same. If you do not have flavors, the current solution already works for 25.x.

**Comment by dodgex** [comment]
I'll see what i can do.

I think i need to check the following, or am i missing a case?

Processor | Flavor | Split | Description
------------- | ------------- | ------------- | -------------
APT | :heavy_multiplication_x: | :heavy_multiplication_x:  | no flavor or split
APT | :heavy_multiplication_x: | :heavy_check_mark: | no flavor but split
APT | :heavy_check_mark: | :heavy_multiplication_x: | flavor but no split
APT | :heavy_check_mark: | :heavy_check_mark: | flavor and split
KAPT | :heavy_multiplication_x: | :heavy_multiplication_x:  | no flavor or split
KAPT | :heavy_multiplication_x: | :heavy_check_mark: | no flavor but split
KAPT | :heavy_check_mark: | :heavy_multiplication_x: | flavor but no split
KAPT | :heavy_check_mark: | :heavy_check_mark: | flavor and split

**Comment by WonderCsabo** [comment]
I think this covers everything. Nice table! :)

**Comment by dodgex** [comment]
@WonderCsabo although I don't what to get an answer... this is yet again a situation that makes me think of having some extra test cases. not only the compile and functional test we have right now but also something like a multi module gradle project that test like the latest release and maybe support for upcoming majors like the 3.0 alphas. and there we could have small sample projects using these diffrent setups. this way we can (more or less) early detect issues with new versions or regressions with old versions.

**Comment by salacr** [comment]
Hi,
I have same issue if I can somehow assist please let me know.
Thanks

**Comment by rafagcamargo** [comment]
Hello guys!

I'm having the exactly same problem using version `4.3.1`:

`androidannotations.log:`
```
18:16:39.567 [Task worker for ':' Thread 3] ERROR o.a.i.h.AndroidManifestFinder:147 - Could not find the AndroidManifest.xml file, using  generation folder [/Users/rgonzagacamargo/Developer/git/mobile-android/appName/build/generated/source/apt/dev/debug])
18:17:27.871 [Task worker for ':'] ERROR o.a.i.h.AndroidManifestFinder:147 - Could not find the AndroidManifest.xml file, using  generation folder [/Users/rgonzagacamargo/Developer/git/mobile-android/appName/build/generated/source/apt/dev/debug])
```
Here's my configuration:

`classpath 'com.android.tools.build:gradle:3.0.0'`

```
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId project.appPackage

        minSdkVersion 19
        targetSdkVersion 25

        multiDexEnabled true // Enabling multidex support.

    }

    splits {
        // Configures screen ABI split settings
        abi {
            // Enable ABI APK splits
            enable true

            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for x86, armeabi-v7a, and mips

            // Resets the list of ABIs that Gradle should create APKs for to none
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for
            include "arm64-v8a", "armeabi-v7a"

            // Specify that we want to also generate a universal APK that includes all ABIs
            universalApk true
        }
    }
}
```

Is there any update related to this issue?

Thank you!

**Comment by dodgex** [comment]
I just invested some time to review the issue related to splits. unfortunately we have no indication if we have a build with split. 

While we could find a related `AndroidManifest.xml` I'm not sure if we can ensure to pick the correct one...

Not sure what might be the best practice to solve that.

**Comment by WonderCsabo** [comment]
@dodgex we could just use the AndroidManifest.xml of a random split (inside the variant). I think the manifests between split does not really differ. WDYT?

**Comment by dodgex** [comment]
I have no idea,.. I had the same thought about picking a random one, but i think it is possible to have custom code and manifest per split. e.g on x86 there might is a special config for the awesome x86 native lib used... not sure.

But i think this would be our best bet. as i have not found a way to get on the current split mode from the annotation processor.

**Comment by WonderCsabo** [comment]
Okay, lets stay with the random one for now.

**Comment by rafagcamargo** [comment]
Thank you guys! Our app currently does not have specific `AndroidManifest.xml` file per architecture, random file would fix the current problem.

**Comment by Waxhaw** [comment]
This issue resurfaces in the latest Android Studio build.

Android Studio 3.3 Canary 2
Build #AI-181.5281.24.33.4869471, built on June 29, 2018
JRE: 1.8.0_152-release-1136-b04 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

error: Could not find the AndroidManifest.xml file, using  generation folder [/Users/ed/sl-android/app/build/generated/source/apt/debug])

Having to go down this path for Material Design artifacts that I need.  Jumped off the cliff of 'JetPack' and it appears my JetPack isn't starting...   sigh

**Comment by mortenholmgaard** [comment]
I also get this error now when I upgraded to use the new gradle version 4.6 and build tools 3.2.0
When I change back to gradle 4.4 and build tools 3.1.4 the problem is gone! @dodgex 

I have multiple flavors and this kapt configuration:
```
kapt {
    arguments {
        arg("resourcePackageName", android.defaultConfig.applicationId)
    }
}
```

**Comment by WonderCsabo** [comment]
The Android Gradle Plugin version 3.2.0 changed the manifest location again. We already fix that, you should try the `SNAPSHOT` release.

**Comment by rafagcamargo** [comment]
@WonderCsabo is there any plan to release 4.5 version? Thank you.

**Comment by mihaiAdascalitei** [comment]
I had the same problem today and after reading the documentation I found that you can set the default manifest path. I solved it by adding into `buld.gradle(Module:app)` into `defaultConfig{..} `

`javaCompileOptions {
            annotationProcessorOptions {

                
                arguments = ["androidManifestFile": "D:\\Projects\\Android-Project\\app\\src\\main\\AndroidManifest.xml"] //add your path to AndroidManifest.xml
            }
        }`

**Comment by luisfernandezbr** [comment]
@mihaiAdascalitei 
Thanks for your solution. A little bit improvement.

```
javaCompileOptions {
    annotationProcessorOptions {
        arguments = [
            "androidManifestFile": "$projectDir/src/main/AndroidManifest.xml".toString()
        ]
    }
}

Thanks @willPasco

**Comment by juarezfranco** [comment]
Thanks for your solution. That works for me.

**Comment by krischik** [comment]
@luisfernandezbr which parent tag does the `javaCompileOptions` go into?

**Comment by krischik** [comment]
Found it:

```grovy
android {
   …
   defaultConfig {
      …
      javaCompileOptions {
         annotationProcessorOptions {
            arguments = [
                "androidManifestFile": "$projectDir/src/main/AndroidManifest.xml".toString()
            ]
         } // annotationProcessorOptions
      } // javaCompileOptions
   } // defaultConfig
   …
} // android 
```

**Comment by dodgex** [comment]
@krischik if you are using AndroidStudio 3.5 and getting manifest not found, test the 4.7.0-SNAPSHOT of AA. it contains an updated version of the AndroidManifestFinder that works with AS3.5

**Comment by mihaiAdascalitei** [comment]
@krischik the way of doing it was already described in my response above :) https://github.com/androidannotations/androidannotations/issues/2034#issuecomment-425137676

**Comment by krischik** [comment]
> @krischik the way of doing it was already described in my response

No it wasn't. Your response was incomplete. It was missing:

```
android {
   …
   defaultConfig {
```

You response was It was typical power user response missing important context informations because you thought _“everybody”_ would know the correct place to put the code snippet.

**Comment by mihaiAdascalitei** [comment]
@krischik the only problem is that you don't understand how to properly read a response nor appreciate the fact that is offered to you. It's clearly explained where to put it " I solved it by adding into buld.gradle(Module:app) into defaultConfig{..}". More of it, it's nice that everybody else managed to understand it :).
