### ISSUE TITLE
Robolectric java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by tonyyang924** [androidannotations/androidannotations#2141]
**AndroidAnnotations version**: 4.4

**Android compile SDK version**:  27

**Annotated code**:
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk=21)
public class BDD757M1DomainInvitePresenterTest {

    MainActivity_ activity;

    Contract.View view;

    @Before
    public void setUp() throws Exception {

        activity = Robolectric.buildActivity(MainActivity_.class).create().get();

        // given
        view = new MockView();

       
    }

    @Test
    public void shouldPassNonEmptyTitle() {
        // then
        Assert.assertEquals(true, ((MockView) view).isNonEmptyTitle);
    }
```

**Stacktrace in case of AA crash**:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Exception in thread "main" java.lang.NoSuchMethodError: org.robolectric.annotation.Config$Builder.defaults()Lorg/robolectric/annotation/Config$Builder;
	at org.robolectric.ConfigMerger.getConfig(ConfigMerger.java:38)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:475)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:254)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

Process finished with exit code 1
Empty test suite.

**Comment by dodgex** [comment]
I'm pretty sure this is not an AndroidAnnotations issue, you should file an issue at robolectric repository
