### ISSUE TITLE
NullPointer exception after start an activity with IntentBuilder from fragment

### ISSUE THREAD

**Issue by robsonbbs** [androidannotations/androidannotations#2187]
**AndroidAnnotations version**
4.5.2

**Android compile version**
27

**Annotated code**:
```@EActivity(R.layout.activity_main)
public class MainActivity extends BaseSubscribeActivity implements MainContract.MainView,
        NavigationView.OnNavigationItemSelectedListener {
    private final int REQUEST_NEW_SERVICE = 21;
    @Bean
    MainPresenter presenter;
    @Bean
    UserApi userApi;

    @ViewById
    TabLayout tabLayout;
    @ViewById
    ViewPager viewPager;
    @ViewById
    Toolbar toolbar;
    @ViewById
    NavigationView navigationView;
    @ViewById
    DrawerLayout drawerLayout;
    @ViewById
    FrameLayout flBadgeExecution, flBadgeReceived;
    @ViewById
    FloatingActionButton btnAdd, btnRefund, btnOrderService, btnClient, btnCollaborator;
    @ViewById
    TextView tvBadgeReceived, tvBadgeExecution, btnRefundTxt, btnOrderServiceTxt, btnClientTxt,
            btnCollaboratorTxt;
    private boolean isFloatingOpen;
    private boolean updateReceiveds;
    private NotificationManager mNotifyManager;
    private Notification.Builder mBuilder;
    private SocketUtil socketUtil;
    private FilterOrder filterOrder;
    private FilterOrderDialog filterDialog;

    @AfterViews
    public void init() {
        presenter.setView(this);
        setSupportActionBar(toolbar);
        startLocation();

        filterOrder = new FilterOrder();
        filterOrder.setPeriodType(PeriodTypeEnum.CREATED_AT);
        filterDialog = new FilterOrderDialog(this, R.style.Theme_Filter, filterOrder, new FilterListener() {
            @Override
            public void filter() {
                post(filterOrder);
            }
        });

        filterDialog.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialogInterface) {
                filterDialog.setFilterFieldsValues();
            }
        });

        filterDialog.setOnDismissListener(new DialogInterface.OnDismissListener() {
            @Override
            public void onDismiss(DialogInterface dialogInterface) {
                filterDialog.clearFilterFields();
            }
        });

        socketUtil = new SocketUtil();
        socketUtil.init(session.getTokenUser(), new SocketEventListener() {
            @Override
            public void onWorkspaceUpdate() {
                presenter.updateRoleConfigurations();
            }

            @Override
            public void onConnect() {
                presenter.updateRoleConfigurations();
            }
        });

        if (session.getUserSession() != null) {
            Crashlytics.setUserIdentifier(session.getUserSession().getId());
            Crashlytics.setUserName(session.getUserSession().getName());
            Crashlytics.setUserEmail(session.getUserSession().getEmail());
        }

        btnRefundTxt.setVisibility(View.GONE);
        btnOrderServiceTxt.setVisibility(View.GONE);
        btnClientTxt.setVisibility(View.GONE);
        btnCollaboratorTxt.setVisibility(View.GONE);
        btnRefund.hide();
        btnOrderService.hide();
        btnClient.hide();
        btnCollaborator.hide();

        tabLayout.setTabTextColors(ContextCompat.getColor(this, R.color.colorAccent),
                ContextCompat.getColor(this, R.color.colorAccent));
        tabLayout.setBackgroundColor(ContextCompat.getColor(this, android.R.color.white));
        tabLayout.addTab(tabLayout.newTab().setText(getResources().getText(R.string.receive)));
        tabLayout.addTab(tabLayout.newTab().setText(getResources().getText(R.string.execution)));
        tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

        viewPager.addOnPageChangeListener(new TabLayout.TabLayoutOnPageChangeListener(tabLayout));

        ArrayList<Fragment> listFragment = new ArrayList<>();
        listFragment.add(OrderFragment_.builder().firstColumn(true).build());
        listFragment.add(OrderFragment_.builder().firstColumn(false).build());
        viewPager.setOffscreenPageLimit(listFragment.size());
        viewPager.setAdapter(new PagerAdapterFragment(getSupportFragmentManager(), listFragment));

        tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
            @Override
            public void onTabSelected(TabLayout.Tab tab) {
                if (isFloatingOpen) {
                    closeFloatingMenu();
                }
                viewPager.setCurrentItem(tab.getPosition());
            }

            @Override
            public void onTabUnselected(TabLayout.Tab LayoutTab) {

            }

            @Override
            public void onTabReselected(TabLayout.Tab LayoutTab) {

            }
        });

        drawerLayout.addDrawerListener(new DrawerLayout.DrawerListener() {
            @Override
            public void onDrawerSlide(@NonNull View drawerView, float slideOffset) {

            }

            @Override
            public void onDrawerOpened(@NonNull View drawerView) {
                if (isFloatingOpen) {
                    closeFloatingMenu();
                }
            }

            @Override
            public void onDrawerClosed(@NonNull View drawerView) {

            }

            @Override
            public void onDrawerStateChanged(int newState) {

            }
        });

        setupMenu();

        OneSignal.idsAvailable(new OneSignal.IdsAvailableHandler() {
            @Override
            public void idsAvailable(String userId, String registrationId) {
                if (registrationId != null) {
                    presenter.updateDevice(userId);
                }
            }
        });

        presenter.getPendencyType();
        presenter.getUnproductiveType();

        Intent resultIntent = new Intent(this, MainActivity.class);
        PendingIntent resultPendingIntent =
                PendingIntent.getActivity(
                        this,
                        0,
                        resultIntent,
                        PendingIntent.FLAG_UPDATE_CURRENT
                );

        mNotifyManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        mBuilder = new Notification.Builder(getApplicationContext())
                .setSmallIcon(R.drawable.ic_stat_onesignal_default)
                .setLargeIcon(ImageUtils.drawableToBitmap(ContextCompat
                        .getDrawable(this, R.drawable.ic_btime)))
                .setContentIntent(resultPendingIntent);
    }
```

**Expected generated code**

```//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.5.2.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package btime.com.br.app.view.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import btime.com.br.app.R;
import btime.com.br.app.Session_;
import btime.com.br.app.presenter.MainPresenter_;
import btime.com.br.app.util.LocationController_;
import btime.com.br.core.api.users.UserApi_;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.builder.PostActivityStarter;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(R.layout.activity_main);
    }

    @Override
    public<T extends View> T internalFindViewById(int id) {
        return ((T) this.findViewById(id));
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        this.locationController = LocationController_.getInstance_(this);
        this.session = Session_.getInstance_(this);
        this.presenter = MainPresenter_.getInstance_(this);
        this.userApi = UserApi_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MainActivity_.IntentBuilder_(fragment);
    }

    public static MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.tabLayout = hasViews.internalFindViewById(R.id.tab_layout);
        this.viewPager = hasViews.internalFindViewById(R.id.view_pager);
        this.toolbar = hasViews.internalFindViewById(R.id.toolbar);
        this.navigationView = hasViews.internalFindViewById(R.id.navigation_view);
        this.drawerLayout = hasViews.internalFindViewById(R.id.drawer_layout);
        this.flBadgeExecution = hasViews.internalFindViewById(R.id.fl_badge_execution);
        this.flBadgeReceived = hasViews.internalFindViewById(R.id.fl_badge_received);
        this.btnAdd = hasViews.internalFindViewById(R.id.btn_add);
        this.btnRefund = hasViews.internalFindViewById(R.id.btn_refund);
        this.btnOrderService = hasViews.internalFindViewById(R.id.btn_order_service);
        this.btnClient = hasViews.internalFindViewById(R.id.btn_client);
        this.btnCollaborator = hasViews.internalFindViewById(R.id.btn_collaborator);
        this.tvBadgeReceived = hasViews.internalFindViewById(R.id.tv_badge_received);
        this.tvBadgeExecution = hasViews.internalFindViewById(R.id.tv_badge_execution);
        this.btnRefundTxt = hasViews.internalFindViewById(R.id.btn_refund_txt);
        this.btnOrderServiceTxt = hasViews.internalFindViewById(R.id.btn_order_service_txt);
        this.btnClientTxt = hasViews.internalFindViewById(R.id.btn_client_txt);
        this.btnCollaboratorTxt = hasViews.internalFindViewById(R.id.btn_collaborator_txt);
        if (this.btnAdd!= null) {
            this.btnAdd.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnAdd();
                }
            }
            );
        }
        if (this.btnRefund!= null) {
            this.btnRefund.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnRefund();
                }
            }
            );
        }
        if (this.btnOrderService!= null) {
            this.btnOrderService.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnOrderService();
                }
            }
            );
        }
        if (this.btnClient!= null) {
            this.btnClient.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnClient();
                }
            }
            );
        }
        if (this.btnCollaborator!= null) {
            this.btnCollaborator.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnCollaborator();
                }
            }
            );
        }
        init();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  21 :
            {
                MainActivity_.this.onResult(resultCode);
                break;
            }
            case  16 :
            {
                MainActivity_.this.onResultChecklist(resultCode, data);
                break;
            }
            case  15 :
            {
                MainActivity_.this.onResultCustomer(resultCode, data);
                break;
            }
            case  14 :
            {
                MainActivity_.this.onResultOrder(resultCode, data);
                break;
            }
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<MainActivity_.IntentBuilder_>
    {
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, MainActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public PostActivityStarter startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode, lastOptions);
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        context.startActivity(intent, lastOptions);
                    }
                }
            }
            return new PostActivityStarter(context);
        }
    }
}
```
**Actual generated code**

```//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.5.2.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package btime.com.br.app.view.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import btime.com.br.app.R;
import btime.com.br.app.Session_;
import btime.com.br.app.presenter.MainPresenter_;
import btime.com.br.app.util.LocationController_;
import btime.com.br.core.api.users.UserApi_;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.builder.PostActivityStarter;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(R.layout.activity_main);
    }

    @Override
    public<T extends View> T internalFindViewById(int id) {
        return ((T) this.findViewById(id));
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        this.locationController = LocationController_.getInstance_(this);
        this.session = Session_.getInstance_(this);
        this.presenter = MainPresenter_.getInstance_(this);
        this.userApi = UserApi_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MainActivity_.IntentBuilder_(fragment);
    }

    public static MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.tabLayout = hasViews.internalFindViewById(R.id.tab_layout);
        this.viewPager = hasViews.internalFindViewById(R.id.view_pager);
        this.toolbar = hasViews.internalFindViewById(R.id.toolbar);
        this.navigationView = hasViews.internalFindViewById(R.id.navigation_view);
        this.drawerLayout = hasViews.internalFindViewById(R.id.drawer_layout);
        this.flBadgeExecution = hasViews.internalFindViewById(R.id.fl_badge_execution);
        this.flBadgeReceived = hasViews.internalFindViewById(R.id.fl_badge_received);
        this.btnAdd = hasViews.internalFindViewById(R.id.btn_add);
        this.btnRefund = hasViews.internalFindViewById(R.id.btn_refund);
        this.btnOrderService = hasViews.internalFindViewById(R.id.btn_order_service);
        this.btnClient = hasViews.internalFindViewById(R.id.btn_client);
        this.btnCollaborator = hasViews.internalFindViewById(R.id.btn_collaborator);
        this.tvBadgeReceived = hasViews.internalFindViewById(R.id.tv_badge_received);
        this.tvBadgeExecution = hasViews.internalFindViewById(R.id.tv_badge_execution);
        this.btnRefundTxt = hasViews.internalFindViewById(R.id.btn_refund_txt);
        this.btnOrderServiceTxt = hasViews.internalFindViewById(R.id.btn_order_service_txt);
        this.btnClientTxt = hasViews.internalFindViewById(R.id.btn_client_txt);
        this.btnCollaboratorTxt = hasViews.internalFindViewById(R.id.btn_collaborator_txt);
        if (this.btnAdd!= null) {
            this.btnAdd.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnAdd();
                }
            }
            );
        }
        if (this.btnRefund!= null) {
            this.btnRefund.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnRefund();
                }
            }
            );
        }
        if (this.btnOrderService!= null) {
            this.btnOrderService.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnOrderService();
                }
            }
            );
        }
        if (this.btnClient!= null) {
            this.btnClient.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnClient();
                }
            }
            );
        }
        if (this.btnCollaborator!= null) {
            this.btnCollaborator.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.onBtnCollaborator();
                }
            }
            );
        }
        init();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  21 :
            {
                MainActivity_.this.onResult(resultCode);
                break;
            }
            case  16 :
            {
                MainActivity_.this.onResultChecklist(resultCode, data);
                break;
            }
            case  15 :
            {
                MainActivity_.this.onResultCustomer(resultCode, data);
                break;
            }
            case  14 :
            {
                MainActivity_.this.onResultOrder(resultCode, data);
                break;
            }
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<MainActivity_.IntentBuilder_>
    {
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, MainActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public PostActivityStarter startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode, lastOptions);
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        context.startActivity(intent, lastOptions);
                    }
                }
            }
            return new PostActivityStarter(context);
        }
    }
}
```
**Exception stacktrace**
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.content.ComponentName.<init>(ComponentName.java:128)
       at android.content.Intent.<init>(Intent.java:4873)
       at org.androidannotations.api.builder.IntentBuilder.<init>(IntentBuilder.java:34)
       at org.androidannotations.api.builder.ActivityIntentBuilder.<init>(ActivityIntentBuilder.java:46)
       at btime.com.br.app.view.activity.MainActivity_$IntentBuilder_.<init>(MainActivity_.java:203)
       at btime.com.br.app.view.activity.MainActivity_.intent(MainActivity_.java:84)
       at btime.com.br.app.view.fragment.PasswordFragment.onLogin(PasswordFragment.java:143)
       at btime.com.br.app.presenter.LoginPresenter$1.success(LoginPresenter.java:45)
       at btime.com.br.app.presenter.LoginPresenter$1.success(LoginPresenter.java:42)
       at btime.com.br.app.usecase.login.LoginUseCase$1.success(LoginUseCase.java:29)
       at btime.com.br.app.usecase.login.LoginUseCase$1.success(LoginUseCase.java:26)
       at btime.com.br.core.api.auth.AuthApi$2.onNext(AuthApi.java:95)
       at btime.com.br.core.api.auth.AuthApi$2.onNext(AuthApi.java:85)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6253)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by robsonbbs** [comment]
**Start activity call**
```@Override
    public void onLogin(@NonNull UserSession userSession) {
        session.setUserSession(userSession);
        MainActivity_.intent(this).start();
        getActivity().finish();
    }
```

**Comment by WonderCsabo** [comment]
I think this happens because your `PasswordFragment` is not yet attached to the `Activity`. We call `getActivity()` on your `Fragment`, but that will return `null`. Please double check that.

**Comment by robsonbbs** [comment]
Maybe you're right. I will check that and let you know. 

Tks in advance!
