### ISSUE TITLE
I start my project then crush , just only see these logs , i dont know what happened

### ISSUE THREAD

**Issue by Billvvy** [androidannotations/androidannotations#2236]
E/ExceptionHandler: [main] FrameworkExceptionHandler: This is the exception that cause Crash.
                                                              
                                                              java.lang.NoSuchMethodError: No interface method internalFindViewById(I)Landroid/view/View; in class Lorg/androidannotations/api/view/HasViews; or its super classes (declaration of 'org.androidannotations.api.view.HasViews' appears in /data/app/com.hznsyh-2/base.apk:classes2.dex)
                                                                  at com.hznsyh.launcher.activity.MainActivity_.onViewChanged(MainActivity_.java:82)
                                                                  at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(Unknown Source)
                                                                  at com.hznsyh.launcher.activity.MainActivity_.setContentView(MainActivity_.java:53)
                                                                  at com.hznsyh.launcher.activity.MainActivity_.onCreate(MainActivity_.java:37)
                                                                  at android.app.Activity.performCreate(Activity.java:6720)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                  at com.alipay.mobile.quinox.activity.QuinoxInstrumentation.callActivityOnCreate(QuinoxInstrumentation.java:519)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:241)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by XieEDeHeiShou** [comment]
Can you provide more infomation? Such as which version of AA are you using, and gradle and so on.

I find this method in 4.6.0's `HasView`:
```java
package org.androidannotations.api.view;

import android.view.View;

public interface HasViews {
	<T extends View> T internalFindViewById(int id);
}
```

**Comment by jielundewode** [comment]
looks like dex excedded 64k
