### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class com.android.tools.r8.GeneratedOutlineSupport: 

### ISSUE THREAD

**Issue by Maxwell6635** [androidannotations/androidannotations#2240]
Compile with R8 enabled iit crash

**AndroidAnnotations version**: 4.6.0

**Android compile SDK version**: 28

**Annotated code**:
```java
@EBean(scope = EBean.Scope.Singleton)
public class BaseHelper {

    @RootContext
    public Context context;

    private Gson gson;
```
**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:
    java.lang.VerifyError: Verifier rejected class com.android.tools.r8.GeneratedOutlineSupport: com.lib.base.BaseHelper_ com.android.tools.r8.GeneratedOutlineSupport.outline6(org.androidannotations.api.view.OnViewChangedListener) failed to verify: com.lib.base.BaseHelper_ com.android.tools.r8.GeneratedOutlineSupport.outline6(org.androidannotations.api.view.OnViewChangedListener): [0x3] 'this' argument 'Reference: org.androidannotations.api.view.OnViewChangedListener' not instance of 'Reference: androidx.fragment.app.Fragment' (declaration of 'com.android.tools.r8.GeneratedOutlineSupport' appears in /data/app/com.advus.patient-1/base.apk)
        at com.android.tools.r8.GeneratedOutlineSupport.outline35(outline)
        at androidx.multidex.MultiDex.<clinit>(MultiDex.java:8)
        at androidx.multidex.MultiDex.install(MultiDex.java)
        at androidx.multidex.MultiDexApplication.attachBaseContext(MultiDexApplication.java:2)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5632)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by ajoz** [comment]
Why was this ticket closed? What is the resolution? I am experiencing the same issue and would like to understand what can cause such exceptions.
