### ISSUE TITLE
Project unbuildable with classes at the root src/main/java level 

### ISSUE THREAD

**Issue by peterplamenovpenchev** [androidannotations/androidannotations#2276]
Hi all, as the issue title states after I updated the tools that I am using the project build started to fail. I will demonstrate my setup with the build scripts that I am using:

**Setup:**

`buildSrc/build.gradle.kts`
```
repositories {
  jcenter()
}

plugins {
  `kotlin-dsl`
}
```

`Plugins.kt`
```
val PluginDependenciesSpec.android
  get() = id("com.android.application")

val PluginDependenciesSpec.kotlin
  get() = id("kotlin-android")

val PluginDependenciesSpec.kotlinExtensions
  get() = id("kotlin-android-extensions")

val PluginDependenciesSpec.apollo
  get() = id("com.apollographql.apollo")
```

`Versions.kt`
```
object Versions {
  object Environment {
    val java = JavaVersion.VERSION_1_8
    const val kotlin = "1.3.72"
    const val buildTools = "4.0.0"

    const val compileSdk = 29
    const val minSdk = 24
    const val targetSdk = 29

    const val appId = "com.furian.gitviewer"
    const val code = 1
    const val name = "1.0"
  }

  object Tools {
    const val apollo = "2.1.0"
    const val okHttpLogging = "4.4.0"
    const val material = "1.1.0"
    const val timber = "4.7.1"
  }

  object AndroidX {
    const val appCompat = "1.1.0"
    const val kotlinExtensions = "1.2.0"
    const val archComponents = "2.2.0"
    const val navigation = "2.2.1"
    const val constraintLayout = "1.1.3"
    const val swipeRefreshLayout = "1.0.0"
    const val recyclerView = "1.1.0"
  }
}
```

`app/build.gradle.kts`
```
plugins {
  android
  kotlin
  kotlinExtensions
  apollo
  kotlin("kapt")
}

android {
  defaultConfig {
    with(Versions.Environment) {
      compileSdkVersion(compileSdk)
      minSdkVersion(minSdk)
      targetSdkVersion(targetSdk)

      applicationId = appId
      versionCode = code
      versionName = name

      compileOptions {
        sourceCompatibility = java
        targetCompatibility = java
      }

      kotlinOptions { jvmTarget = java.toString() }
    }
  }
}

apollo { generateKotlinModels.set(true) }

dependencies {
  kotlinStdLib()
  androidX()
  tools()

  kapt("org.androidannotations:androidannotations:4.7.0")
  implementation("org.androidannotations:androidannotations-api:4.7.0")
}
```

`gradle-wrapper.properties`
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
```

**Problem:**

This setup was building the project successfully before I have updated to the latest Android Studio (v. 4.0 released on May 20 2020). With this update I also bumped the following version numbers:

```
const val kotlin = "1.3.71" to "1.3.72"
const val buildTools = "3.6.2" to "4.0.0"
```

Right now it gives me this error:

<img width="1680" alt="Screenshot 2020-06-17 at 22 20 05" src="https://user-images.githubusercontent.com/22145248/84942705-ec828000-b0eb-11ea-824a-4863b83d335e.png">

From this screenshot I can see that the build fails at this step `:app:kaptDebugKotlin`, because it cannot find the apollo (https://github.com/apollographql/apollo-android) generated classes.

We can also see that the classes that the compiler complains about are actually there. They just don't belong to any package.

A little background to what apollo does:
- it generates kotlin classes from a `queries.graphql` file which contains ordinary GraphQL queries

If it is of any help: 

- what I have found out is that if I rename the query (and hence the name of its kotlin class) & hit run (without clean) the build succeeds. I can't build the project from scratch though
(`clean + build`).

- I have tried to turn off the `Incremental annotation processing` (the warning fix) by using this flag `kapt.incremental.apt=false` in the `gradle.properties`, but without any luck

- what is interesting is that it doesn't find the top level class (for instance `PullRequestsQuery`), but finds some of the inner ones (for instance `PullRequestsQuery.Data`).

If I comment out this line from `app/build.gradle.kts` the build succeeds every time:
```
kapt("org.androidannotations:androidannotations:4.7.0")
```

Can someone please help me find a solution to this problem?

Thanks in advance!

**Comment by peterplamenovpenchev** [comment]
Also, here is the stacktrace when `./gradlew build --stacktrace` is executed:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:kaptDebugKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
        at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:334)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.access$000(DefaultAsyncWorkTracker.java:34)
        at org.gradle.internal.work.DefaultAsyncWorkTracker$1.run(DefaultAsyncWorkTracker.java:106)
        at org.gradle.internal.Factories$1.create(Factories.java:26)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:260)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:171)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:165)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withoutProjectLock(StopShieldingWorkerLeaseService.java:95)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:102)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:80)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:68)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:576)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more
Caused by: java.lang.reflect.InvocationTargetException
        at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:158)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:198)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        ... 3 more
Caused by: org.jetbrains.kotlin.kapt3.base.util.KaptBaseError: Error while annotation processing
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:126)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
        at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
        ... 25 more
```

**Comment by dodgex** [comment]
Unfortunately the StackTrace do not point to an exact error related to AA. Everything is eigther `org.gradle` or `org.jetbrains`. This makes it harder.

`Annotation processing classpath: /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/2a25b0074f125381382382e6adb3cfc1/jetified-androidannotations-4.7.0.jar, /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/287e9ccccb82be0feb2f13e871cbc3e5/jetified-androidannotations-api-4.7.0.jar, /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/33b83f09b7501ef571574f29eff4c888/jetified-jcodemodel-3.0.1.jar, /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/6b7754016154ac2eb19654f5216b5d72/jetified-annotations-3.0.1u2.jar, /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/79eff46a13fa7fb0e1108b29b5798b2d/jetified-jcip-annotations-1.0.jar, /Users/peter.penchev/.gradle/caches/transforms-2/files-2.1/fa665507eae41dc7c11f10c1c4fcff32/jetified-jsr305-3.0.1.jar`

Shows that the AA Jars have been "jetified", i have no idea if this could break AA in some way.


But on the other hand the Line `[INFO] org.androidannotations.internal.AndroidAnnotationProcessor: total: 97 ms, init: 97 ms, 0 round(s): ` makes me actually assume that the AA Processor did successfully run.


Can you test if a build w/o graphql would work? Maybe it is some kind of incompat ?

**Comment by peterplamenovpenchev** [comment]
I did manage to build the project successfully. What I did was to create a folder structure under `main/graphql` folder like so:

<img width="292" alt="Screenshot 2020-06-20 at 13 36 31" src="https://user-images.githubusercontent.com/22145248/85199827-165dc180-b2fb-11ea-92c1-118ce42fcd01.png">

This way `Apollo` generates the kotlin classes that wrap the GraphQL queries in their own package that matches the folder structure.

- Before that structure we had the following thing `import RepositoriesQuery`
- Now with the folder structure we have `import com.furian.gitviewer.RepositoriesQuery`

This makes me think that either:
- the build config is not adding the classes without package to the `CLASSPATH` 
- the `kapt` or `AA` do not include such classes in the preprocessor classes set and thus they appear missing

I also can reproduce this behaviour with a vanilla setup that is not influenced by the `Apollo` library like so:

<img width="1677" alt="Screenshot 2020-06-20 at 13 59 01" src="https://user-images.githubusercontent.com/22145248/85200240-5c685480-b2fe-11ea-8eb6-0eae5c773916.png">

**Comment by dodgex** [comment]
I'm pretty sure that this is no AA issue. Maybe `kapt`.

Could you test your case with another annotation processor that is Not AA? 

Also you should  always avoid using the "default package" (aka Not having a package for a class) anyway.

**Comment by peterplamenovpenchev** [comment]
You are right. I tested the exact same setup with this:

```
kapt("com.google.dagger:dagger-compiler:2.28")
```

instead of

```
kapt("org.androidannotations:androidannotations:4.7.0")
```

and it still fails for the same reason. Also I have created a follow up ticket here: https://youtrack.jetbrains.com/issue/KT-39743

About the `default package` thing - you are absolutely correct. I kinda stumbled upon that with the `Apollo` generated classes.

**Comment by dodgex** [comment]
I voted for KT-39743. I hope they'll fix it. But luckily it works when not using the default package.

I'm closing this issue then.
