### ISSUE TITLE
AA KaptException with kotlin 1.4

### ISSUE THREAD

**Issue by dharashahkenya** [androidannotations/androidannotations#2282]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

I am using the latest kotlin version and build plugin version, but kaptRelease task seems to fail due to the error below. Is there anything i can do to prevent this from happening? Or should i use an older version? 

**AndroidAnnotations version**: 4.7.0

**Android compile SDK version**: 29

**Annotated code**:
```java
your code
```

**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:

```
Caused by: org.jetbrains.kotlin.kapt3.base.util.KaptBaseError: Exception while annotation processing
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:83)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:34)
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.androidannotations.logger.appender.FileAppender.open(FileAppender.java:53)
	at org.androidannotations.logger.LoggerContext.setEnvironment(LoggerContext.java:85)
	at org.androidannotations.internal.AndroidAnnotationProcessor.init(AndroidAnnotationProcessor.java:84)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:33)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:170)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:78)
	... 27 more
```

**Comment by dodgex** [comment]
you can use `logAppenderFile=false` in [annotation processor options](https://github.com/androidannotations/androidannotations/blob/develop/examples/kotlin/build.gradle#L44) this disables the attemt to create the logfile. to write logs to the console instead you can use `logAppenderConsole=true`

**Comment by dharashahkenya** [comment]
I see, so was this incorporated in the latest version? Because i downgraded the version to 4.6.0 and it works fine with it. I could give this a try and see how it functions 👍 🙇

**Comment by dodgex** [comment]
This should be part of AA for longer, no idea what exactly causes your exception.

**Comment by WonderCsabo** [comment]
Please check #2267. Seems to be the same issue.
