### ISSUE TITLE
illegalstateexception: Fragment 'foo' did not create a view

### ISSUE THREAD

**Issue by davidjorgensen** [androidannotations/androidannotations#426]
Hi again

In my app, I tend to use a lot of fragments, which also works very well.
However, I also get this error sometimes.

```
12-04 16:15:47.408 E/AndroidRuntime( 3658): FATAL EXCEPTION: main
12-04 16:15:47.408 E/AndroidRuntime( 3658): java.lang.RuntimeException: Unable to start activity ComponentInfo{se.tre.android.friendtones/dk.shape.friendtones.MainActivity_}: android.view.InflateException: Binary XML file 
line #8: Error inflating class fragment
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1659)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2853)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.access$1600(ActivityThread.java:121)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:947)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.os.Handler.dispatchMessage(Handler.java:99)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.os.Looper.loop(Looper.java:123)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.main(ActivityThread.java:3701)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at java.lang.reflect.Method.invokeNative(Native Method)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at java.lang.reflect.Method.invoke(Method.java:507)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at dalvik.system.NativeStart.main(Native Method)
12-04 16:15:47.408 E/AndroidRuntime( 3658): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class fragment
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:587)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:227)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.Activity.setContentView(Activity.java:1657)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at dk.davidj.app.MainActivity_.setContentView(MainActivity_.java:42)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at dk.davidj.app.MainActivity_.onCreate(MainActivity_.java:29)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
12-04 16:15:47.408 E/AndroidRuntime( 3658): ... 12 more
12-04 16:15:47.408 E/AndroidRuntime( 3658): Caused by: java.lang.IllegalStateException: Fragment dk.davidj.app.fragments.Player_ did not create a view.
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:295)
12-04 16:15:47.408 E/AndroidRuntime( 3658): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
12-04 16:15:47.408 E/AndroidRuntime( 3658): ... 22 more
12-04 16:15:47.418 E/Crash Log( 2956): Crash
```

I am not sure if I am doing things incorrectly or what is happening. The above error came when opening the physical keyboard on a sony ericsson phone.

However, I believe it also happens when the app is being resumed after a period of time (when it has to create the view again).

I am using the support library, and it happens on all platforms >2.2 (at least those i have tested.. 2.2, 4.0, 4.1, 4.2.1)

Btw, my activity is using @EActivity(resName="activity_main"), while my fragment is using @EFragment(resName="fragment_player"). Not sure if it makes any difference.

Using AA v2.7.

Any help would be greatly appreciated.
Thanks
David

**Comment by developer-tz** [comment]
How did you solve it ?

**Comment by davidjorgensen** [comment]
Sorry, I cant remember what I did. It's over 2 years ago..

Good luck though
