### ISSUE TITLE
Possible issue with AA adapter on earlier Android build

### ISSUE THREAD

**Issue by davidjorgensen** [androidannotations/androidannotations#647]
Hey everyone

So I have been using AA for quite a while and have never encountered an issue like this before.

This is however, the first time I am using Google Navigation Drawer.

First of, I am using the pattern described in the "cookbook" for using AA in adapters and listviews. I am using a slightly different approach using reflection, but the outcome is the same.

Here is is very shortened. You get the idea.

``` java
View v = NavigationItemRowView_.build(context);
v.bind(object);
```

Not a problem, and never has been.
So since the Navigation Drawer is part of the support library, I naturally assumed it was working on earlier version of Android (2.2 and onward), so I didn't really bother to test it.

But now I did, and it turned out that the app does in fact crash. Not in the Navigation Drawer, but the Adapter loading items into the listview inside the navigation drawer.

Here is the stacktrace

``` java
06-26 16:28:27.362: ERROR/AndroidRuntime(2921): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at android.widget.AbsListView.obtainView(AbsListView.java:1521)
        at android.widget.ListView.makeAndAddView(ListView.java:1749)
        at android.widget.ListView.fillDown(ListView.java:674)
        at android.widget.ListView.fillFromTop(ListView.java:731)
        at android.widget.ListView.layoutChildren(ListView.java:1602)
        at android.widget.AbsListView.onLayout(AbsListView.java:1349)
        at android.view.View.layout(View.java:7320)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:672)
        at android.view.View.layout(View.java:7320)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:342)
        at android.view.View.layout(View.java:7320)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1263)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1137)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1051)
        at android.view.View.layout(View.java:7320)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:342)
        at android.view.View.layout(View.java:7320)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:342)
        at android.view.View.layout(View.java:7320)
        at android.view.ViewRoot.performTraversals(ViewRoot.java:1162)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1882)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
```

trying to debug it a bit I end up with this (inside the _ class)

``` java
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.item_drawer_navigation, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    public static NavigationItemRowView build(Context context) {
        NavigationItemRowView_ instance = new NavigationItemRowView_(context);
        instance.onFinishInflate();
        return instance;
    }
```

and it crashes in the line

``` java
inflate(getContext(), layout.item_drawer_navigation, this);
```

if I remove all items in the adapter, it works fine (of course) and the navigation drawer can open and close as expected (so it is supported by older devices).

I have just tried to update AA to the latest snapshot, but it has not helped.

Any ideas?
Thanks in advance,
David

**Comment by mmarcano** [comment]
Hi, I am trying to use navigation drawer with AndroidAnnotation library, but it has been impossible for me to allow that. Any advice? It seems when I bind the Layout of the activity using  @EActivity it makes the app crush, but when I do the noraml way with setContentView, it works fine. I would really appreciate any advice here.

Thanks

**Comment by WonderCsabo** [comment]
@mmarcano please post a question to stackoverflow with `android-annotations` tag.
