### ISSUE TITLE
 java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to 

### ISSUE THREAD

**Issue by fyname** [androidannotations/androidannotations#777]
@Rest(rootUrl = "http://192.168.19.100:8081/weijia-site-web", converters = { GsonHttpMessageConverter.class })
public interface BmwService {

```
/**
 * @desc 获取服务的json ，服务的json数据必须以List方式转换json
 * @return
 */
@Get("/bmw/getUser")
@Accept(MediaType.APPLICATION_JSON)
List getAllBmw();
```

}

public class ListViewBmwAdapter extends BaseAdapter {

```
private Context context;//运行上下文

private List<BmwDO>                 listItems;//bmw数据集合
private LayoutInflater          listContainer;//视图容器
int                                 itemViewResource;//自定义项视图源

//List<BmwDO> mList = new ArrayList<BmwDO>();
//private BmwDO u;
//private ViewHolder holder =new ViewHolder();
private String tag ="ListViewBmwAdapter";
```

@Override
    public View getView(int position, View convertView, ViewGroup parent) {
        // TODO Auto-generated method stub
        ViewHolder holder = null;

```
    Log.i(tag,"**************getView**********************");
    Log.i(tag,listItems.toString()); 
    Log.i(tag,"**************getView**********************");
    /*
    for (int j=0;j< listItems.size();j++){
        Log.i(tag,"**************getView++**********************");
        Log.i(tag,listItems.get(j).toString()); 
        Log.i(tag,"**************getView++**********************");
    } */

    if (convertView == null) {
        holder = new ViewHolder();
        //获取list_item布局文件的视图
        convertView = listContainer.inflate(this.itemViewResource, null);
        holder.header_ = (TextView) convertView.findViewById(R.id.tx_header_title);
        holder.title_ = (TextView) convertView.findViewById(R.id.txt_title);
        holder.short_ = (TextView) convertView.findViewById(R.id.txt_short_content);
        holder.img_thu = (ImageView) convertView.findViewById(R.id.img_thu);
        convertView.setTag(holder);

    } else {
        holder = (ViewHolder) convertView.getTag();
    }
    //设置文字和图片
    BmwDO item = listItems.get(position);
    holder.header_.setText(item.getUsername());
    holder.title_.setText(item.getFullname());
    holder.short_.setText(item.getEmail());
    return convertView;
}
```

}

10-31 05:12:08.115: ERROR/AndroidRuntime(1474): FATAL EXCEPTION: main
        java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.freesun.weijia.app.android.dataobject.BmwDO
        at com.freesun.weijia.app.android.adapter.ListViewBmwAdapter.getView(ListViewBmwAdapter.java:114)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
        at android.widget.AbsListView.obtainView(AbsListView.java:2177)
        at android.widget.ListView.makeAndAddView(ListView.java:1840)
        at android.widget.ListView.fillDown(ListView.java:675)
        at android.widget.ListView.fillSpecific(ListView.java:1333)
        at android.widget.ListView.layoutChildren(ListView.java:1633)
        at android.widget.AbsListView.onLayout(AbsListView.java:2012)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1141)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4559)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by CrazySnail1** [comment]
hi, did you solve this problem?
