### ISSUE TITLE
java.lang.NoClassDefFoundError: com.googlecode.androidannotations.api.SdkVersionHelper

### ISSUE THREAD

**Issue by lukaspili** [androidannotations/androidannotations#98]
Hello,

I'm trying to configure androidannotations on my project with gradle (using the androidannotations gradle plugin 0.3) and intellij idea.
Everything works fine but when I'm pressing the BACK button to quit the android application, I have the following exception :

```
02-05 11:46:03.501: ERROR/AndroidRuntime(2705): FATAL EXCEPTION: main
        java.lang.NoClassDefFoundError: com.googlecode.androidannotations.api.SdkVersionHelper
        at com.app.activity.ApplicationActivity_.onKeyDown(ApplicationActivity_.java:55)
        at android.view.KeyEvent.dispatch(KeyEvent.java:1326)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2078)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1709)
        at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2566)
        at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2541)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3835)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
        at dalvik.system.NativeStart.main(Native Method)
```

Which is referencing the following statement :

```
@Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }
```

Compilation is OK.
In the project dependencies, I'm including the androidannotations-api jar with scope compile (done by the gradle plugin).
Any idea ?

Thanks,
Lukas

**Comment by Gnanaoly** [comment]
The same issue is coming  if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
 cannot resolve the symbol SdkVersionHelper .  Android annotation 4.4.0 
and internalFindViewById issue
Please let me know any body solution

**Comment by WonderCsabo** [comment]
Hey, we removed `SdkVersionHelper` a long time ago. Be sure to use and only use up-to-date AA versions for all dependencies. Also clear the project. What do you mean by`internalFindViewById` issue?
